const d = new Date();
var t = d.toLocaleTimeString();

describe("Accounting_Sample_Process_Flow/Test_Server", function () {
    beforeEach("Login", function () {
        cy.viewport(1600, 800)
        cy.visit("http://192.168.3.187:7071/web/login/")
        cy.wait(1000)
        cy.get('#login').type('qa_user')       // user input
        cy.get('#password').type('1234')       // password input
        cy.get('.btn').click()                // loggin button click
        cy.wait(1000)
        cy.xpath("//i[@class='oi oi-apps']").click()           //menu bar
        cy.wait(1000)
    })

    it("Purchase Requisition", function () {
        cy.xpath("//a[contains(.,'Purchase')]").click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'New')])[2]").click()
        cy.wait(1000)
        cy.get("#department_id_0").type("DevOps").type('{Enter}')
        cy.wait(1000)
        cy.get("#budget_id_0").type("Entertainment").type('{Enter}')
        cy.wait(1000)
        cy.get("#priority_0").select("High")
        cy.wait(1000)
        cy.get("#requisition_type_0").select("Direct Purchase")
        cy.wait(1000)
        cy.get("#remarks_0").type(`Accounting Automation Testing\n\nDate : ${d}  \nTime : ${t}`)
        cy.wait(1000)
        cy.get('.o_field_x2many_list_row_add > a').click()
        cy.wait(1000)
        cy.get("table[class='o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped']>tbody>tr:first-child>td:first-child").type("T-Shirt")
        cy.wait(1000)
        cy.get("table[class='o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped']>tbody>tr:first-child>td:first-child").type('{downArrow}')
        cy.wait(1000)
        cy.get("table[class='o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped']>tbody>tr:first-child>td:nth-child(5)").type("50")
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Submit')])[1]").should('have.text','Submit').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
    })

    it("Direct Purchase", function(){
        cy.xpath("//a[contains(.,'Purchase')]").click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Orders')]").click()
        cy.wait(1000)
        cy.xpath("//a[contains(.,'Direct Purchase')]").click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'New')])[2]").click()
        cy.wait(1000)
        cy.get("#partner_id_0").type("Vendor 2").type('{Enter}')
        cy.wait(1000)
        cy.get("#purchase_request_id_0").type("PR/00").type('{Enter}')
        cy.wait(1000)
        cy.get("table[class='o_section_and_note_list_view o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped']>tbody>tr:first-child>td:nth-child(11)").type('70')
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Submit')])[1]").should('have.text','Submit').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Confirm Order')])[1]").should("have.text","Confirm Order").click()
        cy.wait(1000)
    })

    it ("Inventory => MRR", function(){
        cy.xpath("//a[contains(.,'Inventory')]").click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Operations')]").click()
        cy.wait(1000)
        cy.xpath("(//a[contains(.,'MRR')])[1]").click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'New')])[2]").click()         //New 
        cy.wait(1000)
        cy.get("#mrr_type_0").select('Direct')         //MRR Type Select
        cy.wait(1000)
        cy.get("#purchase_order_id_0").click()      // Direct and Local
        cy.wait(500)
        cy.get("#purchase_order_id_0").type('{Enter}')
        cy.wait(500)
        cy.xpath("//span[contains(.,'Cancel')]").should('have.text', 'Cancel')
        cy.wait(500)
        cy.xpath("(//span[contains(.,'Send For Review')])[1]").should('have.text', 'Send For Review').click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'Ok')])[1]").click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Reviewed')]").should('have.text', 'Reviewed')
        cy.xpath("//span[contains(.,'Reviewed')]").click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Validate')]").should('have.text', 'Validate').click()
        cy.wait(1000)

    })

    it("Accounting : Purchase Bill", function(){
        cy.xpath("//a[contains(.,'Purchase')]").click()
        cy.xpath("//span[contains(.,'Orders')]").click()
        cy.xpath("//a[contains(.,'Direct Purchase')]").click()
        cy.wait(1000)
        cy.get("table[class='o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped']>tbody>tr:first-child>td:nth-child(2)").click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Create Bill')]").should('have.text','Create Bill').click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Send To HOD')]").should('have.text','Send To HOD').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
    })

    it("Accounting : Journal", function(){
        cy.xpath("//a[contains(.,'Accounting')]").click()
        cy.xpath("//span[contains(.,'Vouchers')]").click()
        cy.xpath("//a[contains(.,'Journal')]").click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'New')])[2]").click()
        cy.wait(1000)
        cy.get("#radio_field_0_purchase").click()
        cy.wait(1000)
        cy.get("#selected_bill_ids_0").type('BILL/2024/').type('{Enter}')
        cy.wait(1000)
        cy.get("#cost_center_id_0").type("Stardust").type('{Enter}')
        cy.wait(1000)
        cy.get("#narrations_0").type(`Accounting Automated Testing\n \nDate: ${d}\n \nTime : ${t}`)
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Submit')])[1]").should('have.text','Submit').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Checked')])[1]").should('have.text', 'Checked').click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Post')]").should('have.text','Post').click()
        cy.wait(1000)
    })

    it("Accounting : Approval for Payment of Bill", function(){
        cy.xpath("//a[contains(.,'Accounting')]").click()
        cy.xpath("//span[contains(.,'Bills')]").click()
        cy.xpath("//a[contains(.,'Approval For Payment Of Bill')]").click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'New')])[2]").click()
        cy.wait(1000)
        cy.get("#partner_id_0").type("Vendor 2").type('{Enter}')
        cy.wait(1000)
        cy.get("#account_head_id_0").click()
        cy.wait(500)
        cy.get("#account_head_id_0").type('{Enter}')
        cy.wait(1000)
        cy.get("#bill_amount_0").type("1000").type('{Enter}')
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Submit')])[1]").should('have.text','Submit').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Review')])[1]").should('have.text','Review').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
    })

    it("Accounting : Payments", function(){
        cy.xpath("//a[contains(.,'Accounting')]").click()
        cy.xpath("//span[contains(.,'Vouchers')]").click()
        cy.xpath("//a[contains(.,'Payments')]").click()
        cy.wait(1000)
        cy.xpath("(//button[contains(.,'New')])[2]").click()
        cy.wait(1000)
        cy.get("#radio_field_0_vendor").click()
        cy.wait(1000)
        cy.get("#partner_id_1").type("Vendor 2").type('{Enter}')
        cy.wait(1000)
        cy.get("#approval_for_payment_bill_ids_0").type("APB/2024/").type('{Enter}')
        cy.wait(1000)
        cy.get("#cost_center_id_0").type("Stardust").type('{Enter}')
        cy.wait(1000)
        cy.get("#narrations_0").type(`Accounting Automated Testing\n \nDate : ${d}\n \nTime: ${t}`)
        cy.wait(1000)
        cy.get(".o_field_x2many_list_row_add > a").click()
        cy.wait(1000)
        cy.get('[data-tooltip-delay="1000"][name="account_id"] > .o_field_widget > .o_field_many2one_selection > .o_input_dropdown > .o-autocomplete > .o-autocomplete--input').type("Test Account Expense")
        cy.wait(1000)
        cy.get('[data-tooltip-delay="1000"][name="credit"] > .o_field_widget > .text-nowrap > .o_input').type("1000")
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Submit')])[1]").should('have.text','Submit').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Approve')])[1]").should('have.text','Approve').click()
        cy.wait(1000)
        cy.xpath("(//span[contains(.,'Checked')])[1]").should('have.text', 'Checked').click()
        cy.wait(1000)
        cy.xpath("//span[contains(.,'Post')]").should('have.text','Post').click()
        cy.wait(1000)
    })

    Cypress.on("uncaught: exception", ()=> false)
})